build:
  stage: build
  tags:
    - docker
  image: tarantool/tarantool:1

  before_script:
    - apk add --no-cache make cmake gcc g++
  script:
    - tarantoolctl rocks make
    - make -C build.luarocks/ ARGS=-VV test
