name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: rosik/setup-tarantool@v1
        with:
          tarantool-version: '2.5'

      - run: echo "TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV
      - run: tarantoolctl rocks new_version --tag $TAG
      - run: tarantoolctl rocks pack luarapidxml-$TAG-1.rockspec

      - uses: tarantool/rocks.tarantool.org/github-action@master
        with:
          auth: ${{ secrets.ROCKS_USERNAME }}:${{ secrets.ROCKS_PASSWORD }}
          files: |
            luarapidxml-${{ env.TAG }}-1.rockspec
            luarapidxml-${{ env.TAG }}-1.src.rock
